-- Phase 2: Supabase / PostgreSQL schema for room occupancy logs.
-- Run this in the Supabase SQL editor.

create table if not exists public.room_logs (
  id bigint generated by default as identity primary key,
  room_name text not null,
  count integer not null check (count >= 0),
  created_at timestamptz not null default now()
);

create index if not exists room_logs_created_at_idx
  on public.room_logs (created_at desc);

create index if not exists room_logs_room_name_created_at_idx
  on public.room_logs (room_name, created_at desc);

alter table public.room_logs enable row level security;

-- These policies are intentionally conservative placeholders.
-- Adjust them to your auth model before exposing the table publicly.
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'room_logs'
      and policyname = 'room_logs_select_authenticated'
  ) then
    create policy room_logs_select_authenticated
      on public.room_logs
      for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'room_logs'
      and policyname = 'room_logs_insert_authenticated'
  ) then
    create policy room_logs_insert_authenticated
      on public.room_logs
      for insert
      to authenticated
      with check (true);
  end if;
end $$;
